DevcampPortfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

DevcampPortfolio/app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class = "app-footer"><%= copyright_generator %></p>
  </div>
</div>

DevcampPortfolio/app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Connor OLeary</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

DevcampPortfolio/app/views/shared/_blog_footer.html.erb
        <footer class="blog-footer">
          <%= copyright_generator%>
          <p>
            <a href="#">Back to top</a>
          </p>
        </footer>

DevcampPortfolio/app/views/shared/_blog_masthead.html.erb
    <div class="blog-header">
      <div class="container">
        <h1 class="blog-title">Blog</h1>
        <p class="lead blog-description">The Blog page.</p>
        <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
      </div>
    </div>

DevcampPortfolio/app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</div>

DevcampPortfolio/app/views/shared/_nav.html.erb
<div class="<%= location %>">
   <div><%= link_to "Home", root_path %></div>
   <div><%= link_to "About", about_path %></div>
   <div><%= link_to "Contact", contact_path %></div>
   <div><%= link_to "Blog", blogs_path %></div>
   <div><%= link_to "Portfolio", portfolios_path %></div>
 </div>

DevcampPortfolio/app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View all Portfolios', portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <%= copyright_generator%>
  </div>
</footer>

DevcampPortfolio/app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio</h1>
    <p class="lead text-muted">These are a few examples of all the steps on my way to become a professional developer</p>
    <p>
      <%= link_to "More about Me", about_path, class: 'btn btn-primary'%>
      <%= link_to "My Blog", blogs_path, class: 'btn btn-secondary'%>
    </p>
  </div>
</section>

DevcampPortfolio/app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Contact</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Connor O'Leary</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>